apiVersion: v1
kind: Service
metadata:
  name: modelbazaar
spec:
  type: {{ .Values.service.type }}
  selector:
    app: modelbazaar
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http